### ISSUE TITLE
Issue when refetching.

### ISSUE THREAD

**Issue by inc16sec** [artflutter/graphql_flutter_bloc#3]
When trying to refetch the data after the page gets disposed and initialized again, it throws an error.

```
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: Unhandled error Exception: Query is not refetch safe occurred in Instance of 'PostsBloc'.
#0      ObservableQuery.refetch
#1      QueryBloc._refetch
<asynchronous suspension>
#0      BlocBase.onError.<anonymous closure>
#1      BlocBase.onError
#2      _rootRunBinary (dart:async/zone.dart:1452:47)
#3      _CustomZone.runBinary (dart:async/zone.dart:1342:19)
#4      _CustomZone.runBinaryGuarded (dart:async/zone.dart:1252:7)
#5      _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:360:15)
#6      _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:378:7)
#7      _BufferingStreamSubscription._addError (dart:async/stream_impl.dart:280:7)
#8      _SyncBroadcastStreamController._sendError.<anonymous closure> (dart:async/broadcast_stream_controller.dart:393:20)
#9      _BroadcastStreamController._forEachListener (dart:async/broadcast_stream_controller.dart:323:15)
#10     _SyncBroadcastStreamController._sendError (dart:async/broadcast_stream_controller.dart:392:5)
#11     _BroadcastStreamController._addError (dart:async/broadcast_stream_controller.dart:290:5)
#12     _rootRunBinary (dart:async/zone.dart:1452:47)
#13     _CustomZone.runBinary (dart:async/zone.dart:1342:19)
#14     _CustomZone.runBinaryGuarded (dart:async/zone.dart:1252:7)
#15     _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:360:15)
#16     _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:378:7)
#17     _BufferingStreamSubscription._addError (dart:async/stream_impl.dart:280:7)
#18     _ForwardingStreamSubscription._addError (dart:async/stream_pipe.dart:128:11)
#19     _ForwardingStream._handleError (dart:async/stream_pipe.dart:95:10)
#20     _ForwardingStreamSubscription._handleError (dart:async/stream_pipe.dart:157:13)
#21     _rootRunBinary (dart:async/zone.dart:1452:47)
#22     _CustomZone.runBinary (dart:async/zone.dart:1342:19)
#23     _CustomZone.runBinaryGuarded (dart:async/zone.dart:1252:7)
#24     _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:360:15)
#25     _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:378:7)
#26     _DelayedError.perform (dart:async/stream_impl.dart:602:14)
#27     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:706:11)
#28     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:663:7)
#29     _rootRun (dart:async/zone.dart:1420:47)
#30     _CustomZone.run (dart:async/zone.dart:1328:19)
#31     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
#32     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276:23)
#33     _rootRun (dart:async/zone.dart:1428:13)
#34     _CustomZone.run (dart:async/zone.dart:1328:19)
#35     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
#36     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276:23)
#37     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#38     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
```

And it directs me to this;
```Dart
 /// Attempts to refetch _on the network_, throwing error if not refetch safe
  ///
  /// **NOTE:** overrides any present non-network-only [FetchPolicy],
  /// as refetching from the `cache` does not make sense.
  Future<QueryResult?> refetch() {
    if (isRefetchSafe) {
      addResult(QueryResult.loading(data: latestResult?.data));
      return queryManager.refetchQuery(queryId);
    }
    throw Exception('Query is not refetch safe');
  }
```

Note that this only happens once I go into a different page and the Posts Page gets disposed.. When I return back to the Posts Page, even tho it initialize it again but the second time when trying to refetch it throws the error above. 
I've tried to change the `FetchPolicy` to `FetchPolicy.networkOnly` but nothing changes.

Best regards.

**Comment by inc16sec** [comment]
Anything here.. @vasilich6107 I hope you have seen this issue that I have posted more than a month ago. I still get the same error whenever I try to refetch the data or fetch more.

**Comment by vasilich6107** [comment]
Hi @inc16sec 
Will check your issue

**Comment by vasilich6107** [comment]
Do you have any code that reproduced the issue?

**Comment by inc16sec** [comment]
> Do you have any code that reproduced the issue?

My code is quite large and complex.. Sorry if I can't make a copy of it.

The issue like I said before shows up only when I dispose of the page (that calls the bloc) and reinitialize it again.

**Comment by vasilich6107** [comment]
I do not have time to address this issue.
Besides I do not feel like it’s related to the lib itself
